name: ${project.artifactId}
main: de.iani.playerUUIDCache.PlayerUUIDCache
version: ${project.version}-${build.number}
description: Cache UUIDs and names to avoid web lookups
authors:
  - Brokkonaut
  - Starjon
api-version: 1.13

commands:
  uuidcache:
    description: PlayerUUIDCache

softdepend: [GlobalDataClient]